//고양이와 개는 몇 마리 있을까
SELECT ANIMAL_TYPE, COUNT(ANIMAL_TYPE) AS 'count' FROM ANIMAL_INS GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE

//동명 동물 수 찾기
SELECT NAME, COUNT(NAME) AS 'COUNT' FROM ANIMAL_INS GROUP BY NAME HAVING COUNT(NAME) >= 2 ORDER BY NAME

//입양 시각 구하기(1)
SELECT HOUR(DATETIME) AS HOUR, COUNT(ANIMAL_ID) AS 'COUNT' FROM ANIMAL_OUTS 
GROUP BY HOUR
HAVING HOUR >= 9 AND HOUR <= 19
ORDER BY HOUR

//입양 시각 구하기(2)
SET @hour := -1;
SELECT (@hour := @hour + 1) as HOUR, 
(SELECT COUNT(*) FROM ANIMAL_OUTS WHERE @hour = HOUR(DATETIME)) AS COUNT
FROM ANIMAL_OUTS
WHERE @hour < 23
